// comentar funcion de cada variable 
export let idUser
export let nombre
export let numerosStream
export let email
export let pass
export let agente
export let apellido
export let borrado
export let cuota
export let estado
export let fechaRregistro
export let followNumero
export let follower
export let gestion
export let idUsuarioModificador
export let idioma
export let ingreso
export let lada
export let moderador
export let monto
export let nickName
export let permiso
export let personaRegalaMas
export let sAdmin
export let ultimaFechaEntrada
export let ultimaFechaModificacion
export let verificado